window.defaultNumber = '+1-877-747-1027';
window.defaultText = 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your ip address |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027';
window.text = {
    'xhamster.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'perfectgirls.net': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'gotporn.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'anysex.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'sex.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'bravotube.net': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'mylust.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'manporn.xxx': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'anybunny.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'txxx.com': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027',
    'findbestsolution.xyz': 'Your Bank Account has been FROZEN effecting immediately due to suspicious activity. Multiple failed login attempts were detected and your |%ip%| has been flagged. All transactions are currently blocked until verification is completed. Call now to verify +1-877-747-1027'
};
